import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
// import { ChakraProvider } from '@chakra-ui/react';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// export default function RootLayout(props: { children: React.ReactNode }) {
//   const { children } = props;
//   return (
//     <html suppressHydrationWarning>
//       <body>
//         <ChakraProvider>{children}</ChakraProvider>
//       </body>
//     </html>
//   );
// }

// app/layout.tsx
import './globals.css';
import Provider from '@/components/ui/Provider';

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html suppressHydrationWarning>
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
