import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Provider from '@/components/ui/Provider';
import { cookies } from 'next/headers';
import HeaderShell from '@/components/layout/HeaderShell';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'publiT',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const cookieStore = await cookies();
  const isLoggedIn = !!cookieStore.get('accessToken');
  const role = cookieStore.get('role')?.value as 'user' | 'admin' | undefined;

  return (
    <html suppressHydrationWarning>
      <body>
        <Provider>
          <HeaderShell isLoggedIn={isLoggedIn} role={role} />
          {children}
        </Provider>
      </body>
    </html>
  );
}
